# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org9
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org9MSP

        # ID to load the MSP definition as
        ID: Org9MSP

        MSPDir: ../organizations/peerOrganizations/org9.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org9MSP.admin', 'Org9MSP.peer', 'Org9MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org9MSP.admin', 'Org9MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org9MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org9MSP.peer')"
