# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org8
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org8MSP

        # ID to load the MSP definition as
        ID: Org8MSP

        MSPDir: ../organizations/peerOrganizations/org8.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org8MSP.admin', 'Org8MSP.peer', 'Org8MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org8MSP.admin', 'Org8MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org8MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org8MSP.peer')"
